
services:
  ocr-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ocr-service
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - SCAN_FOLDER
      - OUTPUT_FOLDER
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_HOST=db
    volumes:
  - ocr_incoming_scan:/app/incoming-scan
  - ocr_output:/app/output
  - ocr_fully_indexed:/app/fully_indexed
  - ocr_partially_indexed:/app/partially_indexed
  - ocr_failed:/app/failed
  - ./logs:/app/logs
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
    ports:
      - "8000:8000"

  db:
    image: mysql:8
    container_name: merbanhub-db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data:
  ocr_incoming_scan:
  ocr_output:
  ocr_fully_indexed:
  ocr_partially_indexed:
  ocr_failed:
